{{- if or (and (eq .Values.autoscaling.enabled false) (gt (.Values.replicaCount | int) 2)) (and (eq .Values.autoscaling.enabled true) (gt (.Values.autoscaling.minReplicas | int) 2)) }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "upday-app.fullname" . }}
  labels:
    {{- include "upday-app.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "upday-app.selectorLabels" . | nindent 6 }}

---
{{- end }}
